### ISSUE TITLE
Incorrect alignements in the model serving page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#572]
icons and label are not properly aligned 

<img width="803" alt="Screenshot 2024-03-18 at 17 01 32" src="https://github.com/projectatomic/ai-studio/assets/1636769/dcf6fb59-8acc-4d19-855e-26ae820a08b9">

**Comment by vrothberg** [comment]
This seems to have been addressed in the meantime.  @axel7083, can you confirm (and close if needed)?

**Comment by axel7083** [comment]
No still not aligned 
![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/38897a3f-9714-47e3-92c9-3e667b6fcca3)

**Comment by vrothberg** [comment]
Thanks!  I missed that it's in the _details_ of a service.
