### ISSUE TITLE
Navbar text and icons not aligned

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-ai-lab#989]
![Screenshot 2024-04-24 at 7 48 19 PM](https://github.com/containers/podman-desktop-extension-ai-lab/assets/6422176/a25f5e08-9f39-4c75-9003-4d47f39efac3)

Looks like the side navbar isn't aligned?

**Comment by slemeur** [comment]
has been fixed

**Comment by cdrage** [comment]
This has not been fixed and I still see this on the main branch, opening up a PR
